#!/usr/bin/env python3
"""
Real email sending test for the EHR system
This script will actually SEND a test email
"""

from app import app, db
from models import Doctor
from utils.mail_helper import send_email
from utils.token_holper import generate_token
import sys


def send_actual_test_email():
    """Send a real test email to verify email functionality"""

    with app.app_context():
        print("🔥 REAL EMAIL SENDING TEST")
        print("=" * 50)

        # Check configuration first
        mail_server = app.config.get("MAIL_SERVER")
        mail_username = app.config.get("MAIL_USERNAME")
        mail_password = app.config.get("MAIL_PASSWORD")

        print(f"Mail Server: {mail_server}")
        print(f"Mail Username: {mail_username}")
        print(f"Mail Password: {'***SET***' if mail_password else '***NOT SET***'}")

        # Check if configuration is complete
        if not all([mail_server, mail_username, mail_password]):
            print("\n❌ EMAIL CONFIGURATION INCOMPLETE!")
            print("Please update config.py with your actual email credentials:")
            print("- MAIL_USERNAME: your Gmail address")
            print("- MAIL_PASSWORD: your Gmail app password")
            print("- MAIL_DEFAULT_SENDER: your email info")
            return False

        # Ask for recipient email
        print(f"\n📧 Ready to send test email from: {mail_username}")
        recipient = input(
            "Enter recipient email address (or press Enter to use sender): "
        ).strip()

        if not recipient:
            recipient = mail_username

        print(f"📤 Sending test email to: {recipient}")

        # Create test email content
        test_token = generate_token(999, "test")

        html_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; }}
                .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                          color: white; padding: 20px; text-align: center; }}
                .content {{ padding: 20px; background: #f9f9f9; }}
                .button {{ background: #667eea; color: white; padding: 12px 24px; 
                          text-decoration: none; border-radius: 5px; display: inline-block; }}
                .footer {{ padding: 20px; text-align: center; color: #666; font-size: 12px; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🏥 EHR System Test Email</h1>
                <p>Email functionality verification</p>
            </div>
            
            <div class="content">
                <h2>✅ Success! Email System is Working</h2>
                <p>This is a <strong>real test email</strong> from your EHR system.</p>
                
                <p><strong>System Details:</strong></p>
                <ul>
                    <li>📧 Sent from: {mail_username}</li>
                    <li>🚀 Server: {mail_server}</li>
                    <li>🔐 Security: TLS Encrypted</li>
                    <li>🎯 Test Token: {test_token[:20]}...</li>
                </ul>
                
                <p>Your EHR system can now:</p>
                <ul>
                    <li>✅ Send registration confirmation emails</li>
                    <li>✅ Send password reset emails</li> 
                    <li>✅ Send professional HTML emails</li>
                    <li>✅ Handle secure token generation</li>
                </ul>
                
                <div style="text-align: center; margin: 20px 0;">
                    <a href="http://localhost:5000" class="button">
                        Visit EHR System Dashboard
                    </a>
                </div>
            </div>
            
            <div class="footer">
                <p>This email was generated by the EHR System email test script.</p>
                <p>If you received this unexpectedly, please ignore it.</p>
            </div>
        </body>
        </html>
        """

        try:
            print("\n🔄 Attempting to send email...")

            # Actually send the email using the real send_email function
            send_email(
                subject="🏥 EHR System - Email Test Successful!",
                recipients=[recipient],
                html=html_content,
            )

            print("✅ EMAIL SENT SUCCESSFULLY!")
            print(f"📬 Check your inbox at: {recipient}")
            print("\n🎉 Your EHR email system is fully functional!")
            return True

        except Exception as e:
            print(f"\n❌ EMAIL SENDING FAILED!")
            print(f"Error: {str(e)}")
            print("\nPossible causes:")
            print("1. Incorrect email credentials in config.py")
            print("2. Gmail app password not set up correctly")
            print("3. Network/firewall blocking SMTP")
            print("4. Gmail 2FA not enabled")
            return False


def show_email_setup_instructions():
    """Show email setup instructions"""
    print("\n" + "=" * 60)
    print("📧 EMAIL SETUP INSTRUCTIONS")
    print("=" * 60)
    print("\n1. 🔧 Update config.py with your credentials:")
    print('   MAIL_USERNAME = "your-email@gmail.com"')
    print('   MAIL_PASSWORD = "your-16-digit-app-password"')
    print('   MAIL_DEFAULT_SENDER = ("EHR System", "your-email@gmail.com")')

    print("\n2. 📱 Gmail App Password Setup:")
    print("   • Go to Google Account Settings")
    print("   • Security → 2-Step Verification")
    print("   • App Passwords → Mail → Generate")
    print("   • Use the 16-digit password in MAIL_PASSWORD")

    print("\n3. 🧪 Test the email system:")
    print("   python send_real_email_test.py")


if __name__ == "__main__":
    print("🚀 EHR System - Real Email Sending Test")
    print("This script will actually send a test email!\n")

    choice = input(
        "Do you want to:\n1. Send test email\n2. Show setup instructions\nChoice (1/2): "
    ).strip()

    if choice == "2":
        show_email_setup_instructions()
    else:
        success = send_actual_test_email()

        if not success:
            print("\n💡 Need help? Run with option 2 for setup instructions.")
