"""Add new enum columns

Revision ID: f523c29e1748
Revises: 
Create Date: 2025-11-02 00:03:48.696092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f523c29e1748'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_type', sa.Enum('CONSULTATION', 'FOLLOW_UP', 'EMERGENCY', 'ROUTINE_CHECKUP', 'SURGERY', 'PROCEDURE', name='appointment_type_enum'), nullable=True))

    with op.batch_alter_table('laboratory_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NORMAL', 'ABNORMAL', 'HIGH', 'LOW', 'CRITICAL', 'PENDING', name='lab_status_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory_result', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('appointment_type')

    # ### end Alembic commands ###
